[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"

[code-nautilus-git]
source = "github"
github = "harry-cpp/code-nautilus"

[python-sklearn-bayes]
source = "github"
github = "AmazaspShumik/sklearn-bayes"

[free-wb]
source = "cmd"
cmd = "curl -s https://d.store.deepinos.org.cn///store/tools/freewb/app.json  | jq -r '.Version'"

[transfer-git]
source = "github"
github = "Mikubill/transfer"

[netease-cloud-music-gtk]
source = "github"
github = "gmg137/netease-cloud-music-gtk"
use_latest_release = true

[aliyundrive-webdav]
source = "github"
github = "messense/aliyundrive-webdav"
use_latest_release = true
