[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
[code-nautilus-git]
source = "github"
github = "harry-cpp/code-nautilus"

[python-sklearn-bayes]
source = "github"
github = "AmazaspShumik/sklearn-bayes"

[free-wb]
source = "cmd"
cmd = "curl -s https://d.store.deepinos.org.cn///store/tools/freewb/app.json  | jq -r '.Version'"