name: CI
on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/archlinux:latest
    steps:
      - name: Install packages
        run: |
          pacman -Syy --noconfirm
          pacman -S --needed --noconfirm git jq aurpublish

      - uses: actions/checkout@main

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
