name: CI
on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/archlinux:latest
    steps:
      - name: Install packages
        run: |
          pacman -Syy --noconfirm
          pacman -S --needed --noconfirm \
            git jq aurpublish nvchecker make pacman-contrib vim \
            sudo

      - uses: actions/checkout@main

      - name: Set ownership
        run: |
          useradd -g wheel -m makepkg
          echo "%wheel ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers
          chown -R makepkg:root $PWD
          git config --global --add safe.directory $PWD

      - name: Config git user and email
        run: |
          git config --global user.name tkit1994 && \
          git config --global user.email ch1994@outlook.com

      - name: Set up github token
        run: |
          su makepkg && \
          cat << EOF > key.toml
          [keys]
          github = "${{ secrets.GITHUB_TOKEN }}"
          EOF

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          config: ${{ secrets.CONFIG }}

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
