name: CI
on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/archlinux:latest
    steps:
      - name: Install packages
        run: |
          pacman -Syy --noconfirm
          pacman -S --needed --noconfirm \
            git jq aurpublish nvchecker make pacman-contrib vim

      - uses: actions/checkout@main

      - name: Set ownership
        run: |
          # this is to fix GIT not liking owner of the checkout dir
          chown -R $(id -u):$(id -g) $PWD
          git config --global user.name tkit1994
          git config --global user.email ch1994@outlook.com

      - name: Set up github token
        run: |
          cat << EOF > key.toml
          [keys]
          github = "${{ secrets.GITHUB_TOKEN }}"
          EOF

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          config: ${{ secrets.CONFIG }}

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
