name: CI
on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/archlinux:latest
    steps:
      - name: Install packages
        run: |
          pacman -Syy --noconfirm
          pacman -S --needed --noconfirm git jq aurpublish nvchecker make

      - name: Set up github token
        run: |
          cat << EOF > key.toml
          [key]
          # github = "${{ secrets.GITHUB_TOKEN }}"
          EOF

      - uses: actions/checkout@main

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary
          config: ${{ secrets.CONFIG }}

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
