name: Auto update
on:
  workflow_dispatch:
  # pull_request:
  # push:
  schedule:
    - cron: 0 17 * * *

jobs:
  update:
    runs-on: ubuntu-latest
    container: archlinux:base-devel
    steps:
      - name: Install packages
        run: |
          pacman -Syu --noconfirm
          pacman -S --needed --noconfirm git nvchecker \
            vim aurpublish make sudo jq pacman-contrib \
            fish

      - name: Configure git makepkg and ssh
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | install -Dm400 /dev/stdin /root/.ssh/aur
          useradd makepkg

      - name: set up ssh config
        run: |
          cat << EOF | tee /root/.ssh/config
          Host aur.archlinux.org
            User aur
            IdentityFile /root/.ssh/aur
            UserKnownHostsFile /dev/null
            StrictHostKeyChecking no
          EOF
      - name: copy ssh directory
        run: cp -rvf /root/.ssh ~/.ssh

      - uses: actions/checkout@main
        with:
          fetch-depth: 0

      - name: Generate key.toml
        run: |
          cat << EOF | tee key.toml
          [keys]
          github = "${{ secrets.GITHUB_TOKEN }}"
          EOF

      - name: config git
        run: |
          chown -R makepkg:root ${GITHUB_WORKSPACE}
          git config --global --add safe.directory ${GITHUB_WORKSPACE}
          git config user.name "github action[bot]"
          git config user.email "action@github.com"

      - name: run update script
        run: ./update.sh

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
