name: nvchecker cron runner
on:
  # pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 16 * * *
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: install packages
        run: sudo apt update && sudo apt install libcurl4-openssl-dev libssl-dev
      - uses: actions/setup-python@main
        with:
          python-version: 3.9 # Version range or exact version of a Python version to use, using SemVer's version range syntax
      - name: install nvchecker
        run: sudo pip3 install nvchecker

      - name: run nvchecker
        id: run_nvchecker
        run: |
          echo "result=$(nvchecker -c nvchecker.toml 2>&1)" >> $GITHUB_OUTPUT
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        if: steps.run_nvchecker.outputs.result != ''
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            The following packages need to be updated:
            ${{ steps.run_nvchecker.outputs.result }}
